BEGIN;

DROP TABLE IF EXISTS 
"list",
"card",
"tag",
"card_has_tag";


CREATE TABLE "list" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "position" integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "card" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" text NOT NULL,
    "position" integer NOT NULL DEFAULT 0,
    "list_id" integer NOT NULL REFERENCES "list"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "color" text NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "card_has_tag" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "card_id" integer NOT NULL REFERENCES "card"("id") ON DELETE CASCADE,
    "tag_id" integer NOT NULL REFERENCES "tag"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);


COMMIT;